variables:
    IMAGE_NAME: dominikjaro/demo-app
    IMAGE_TAG: juice-shop-1.0

stages:
  - cache
  - test
  - build

create_cache:
  image: node:18-bullseye
  stage: cache
  script:
    - yarn install --ignore-engines
  cache:
    key:
      files:
        - yarn.lock
    paths:
        - node_modules/
        - yarn.lock
        - .yarn
    policy: pull-push

yarn_test:
  image: node:18-bullseye
  stage: test
  script:
    - yarn install --ignore-engines
    - yarn test
  cache:
    key:
      files:
        - yarn.lock
    paths:
        - node_modules/
        - yarn.lock
        - .yarn
    policy: pull

gitleaks:
  stage: test
  image:
    name: zricethezav/gitleaks
    #We set the entrypoint so the gitleaks image accepts commands through that entrypoint
    #We set it to empty so it should wait for the script execution
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --source . -f json -r gitleaks.json
  #To filter out False Positives - it only gives WARNING
  allow_failure: true
  artifacts:
    when: always
    paths:
      - gitleaks.json

#SAS tool to scan the static app code for vulnerabilities
# e.g. SQL/NoSQL injection, unsafe regex, cross-site scripting (XSS) and unsecure dependencies
njsscan:
  stage: test
  image: python
  before_script:
    - pip3 install --upgrade njsscan
  script:
    - njsscan --exit-warning . --sarif -o njsscan.sarif
  allow_failure: true
  artifacts:
    when: always
    paths:
      - njsscan.sarif

semgrep:
  stage: test
  image: semgrep/semgrep
  variables: 
    SEMGREP_RULES: p/javascript
  script:
    - semgrep ci --output semgrep.json
  allow_failure: true
  artifacts:
    when: always
    paths:
      - semgrep.json

upload_reports:
  stage: test
  image: python
  script:
    - python 3 upload-reports.py


build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
